import math
x=int(input("Enter a number :"))
y=int(input("Enter a number :"))
print(math.pow(x,y))
print(math.floor(x))
print(math.ceil(y))
print(math.factorial(x))
print(math.sqrt(x))
print(math.fabs(-x))
print(math.sin(x))
print(math.cos(x))
print(math.tan(x))
print(math.trunc(7.9870))
print(math.pi)
print(math.inf>1000)
print(math.inf<1000)

